language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"
env:
  - DJANGO_VERSION=1.4.2
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
before_install:
  - pip install -q django==$DJANGO_VERSION
install:
  - python setup.py develop
script:
  - python setup.py nosetests
matrix:
  exclude:
    - python: "pypy3"
      env: DJANGO_VERSION=1.4.2
    - python: "3.4"
      env: DJANGO_VERSION=1.4.2
    - python: "3.3"
      env: DJANGO_VERSION=1.4.2
    - python: "2.6"
      env: DJANGO_VERSION=1.7
    - python: "2.6"
      env: DJANGO_VERSION=1.8
